### PR TITLE
feat: Add queryComplexityPlugin for query cost analysis

### LINKED ISSUE #307: Plugin: Query Cost Analysis
Hey 👋

I'm researching how to best do Demand Control for GraphQL, and found a great article from Spectrum [here](https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b). Under the title "Implementing Query Cost Analysis", they mention three libraries one can use to manage query costs:

1. [graphql-validation-complexity](https://github.com/4Catalyzer/graphql-validation-complexity)
2. [graphql-cost-analysis](https://github.com/pa-bru/graphql-cost-analysis)
3. [graphql-query-complexity](https://github.com/slicknode/graphql-query-complexity)

Of those, it seems only (2) can be used with Nexus, at it provides the option to pass a `costMap` as an `options` object to the Apollo/Express server. This is usable, but I'd much prefer the option to be able to assign a cost for fields/queries along with the type/query declaration itself, that'd make it much easier to work with. 

The other two rely on either custom directives in the SDL, or custom extensions to the `GraphQLObjectType` as far as I can tell. 

Perhaps it'd be a good idea to add a custom `complexity` or `cost` field to Nexus types/fields, that would allow a cost calculation for queries? Something a la the way [TypeGraphQL](https://typegraphql.ml/docs/complexity.html) does it, perhaps? Or is there another/better way?

Thanks :-)

### PR DESCRIPTION
**Pull request by BjornLuG**
This plugin aims to easily define complexity in nexus field configs. It's based on [graphql-query-complexity](https://github.com/slicknode/graphql-query-complexity) and inspired by TypeGraphQL's built-in [query complexity integration](https://typegraphql.ml/docs/complexity.html).

This will also provide typings for the complexity estimator compared to `graphql-query-complexity`'s [more generic version](https://github.com/slicknode/graphql-query-complexity#creating-custom-estimators).

This plugin will basically copy the exposed `complexity` value and place it in the field's `extensions` object for `graphql-query-complexity` to intercept.

Resolves #307.

Things done:
- [x] Plugin implementation
- [x] Tests
- [x] Docs
- [x] Kitchen sink example

Hope this gets included before final release :)

### CODE REVIEW

**Comment by BjornLuG** [comment]
Prettier's line break below seems to be causing partial coverage. otherwise it should cover all:


It nicely exceeded the 80 characters limit by 1 character..

**Comment by BjornLuG** [comment]
The new prisma framework seems to have a different plugin syntax. Should this be hold off for now?

**Comment by jasonkuhrt** [comment]
@BjornLuG the framework plugin system is a superset. Please see your work through here :) as you’ve already started. We can maybe integrate this plugin automatically like we did with the connection plugin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BjornLuG** [comment]
That's good to know! I took a look at [plugin-prisma](https://github.com/graphql-nexus/plugin-prisma) and it seems like it uses [nexus-prisma](https://github.com/prisma-labs/nexus-prisma) under-the-hood too, with tight integration with Prisma 2.

**Comment by Mika83AC** [comment]
This is a urgently needed plugin as there seems to be no other way to do query cost analysis with nexus.

Highly appreciating any progress here! 👍

**Comment by tgriesser** [comment]
This was quite an impressive PR, very thorough. Released in `0.12.0-rc.10`

**Pull request merged**
